org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
# Mod
enabled_platforms=fabric,neoforge
mod_id=envelope
archives_name=envelope
mod_name=Envelope
mod_version=0.7.5
mod_release_type=release
mod_license=GPLv3
maven_group=io.github.mortuusars.envelope
mod_authors=mortuusars, ceit.wonders
mod_description=Letters and Packages. And Pigeons to deliver them.
mod_page=https://www.curseforge.com/minecraft/mc-mods/envelope
mod_github=https://github.com/mortuusars/Envelope
mod_issues=https://github.com/mortuusars/Envelope/issues
mod_curseforge_project_id=1281170
mod_modrinth_project_id=bINSbhYK
# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
supported_minecraft_versions=1.21,1.21.1
parchment_version=1.21:2024.07.28
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.107.0+1.21.1
# NeoForge
neoforge_version=21.1.225
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=21.1.0
jei_version=19.25.0.322
emi_version=1.1.24+1.21.1
# Mods
sodium_version=mc1.21.1-0.6.13
jade_version=15.10.2
carry_on_version=2.2.3.3
modmenu_version=11.0.3
#- KubeJS
kubejs_version=2101.7.2-build.353
tiny_server_version=1.0.0-build.34
rhino_version=2101.2.7-build.81
#- Create
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
#- Sable - Aeronautics
sable_version=1.2.2
sable_companion_version=1.6.0
create_aeronautics_version=1.2.1
#- Every Compat
everycomp_version=1.21-2.11.49
moonlight_version=1.21.1-3.3.3
# Misc
jupiterVersion=5.11.3